Code_review-1.0
T-Midnight/volga2014 pull request #1
Opened 2016-11-14 12:55 UTC by T-Midnight

2016-11-14 12:59 UTC, T-Midnight commented
@AlisVero, @pavlyukov, @aelaa, @kalashnikovisme

2016-11-14 22:29 UTC, kalashnikovisme commented
все файлы в папке log/ надо положить в .gitignore

2016-11-14 22:35 UTC, kalashnikovisme commented
все файлы в папке tmp/ надо положить в .gitignore

2016-11-14 22:35 UTC, kalashnikovisme requested changes

2016-11-14 22:35 UTC, kalashnikovisme commented on Gemfile
> +gem 'rspec-its'
@T-Midnight зачем нужен этот гем?

2016-11-14 22:35 UTC, kalashnikovisme commented on Gemfile
> +gem 'will_paginate', '3.0.4'
по опыту знаю, что лучше использовать гем kaminari для пагинаци https://github.com/amatsuda/kaminari

но оставь здесь этот

2016-11-14 22:35 UTC, kalashnikovisme commented on app/assets/stylesheets/custom.css.scss
> +/* microposts */
почему microposts?

2016-11-14 22:35 UTC, kalashnikovisme commented on app/assets/stylesheets/custom.css.scss
> +  color: #grayLight;
когда пишешь название цветов `#` в начале не нужна.

2016-11-14 22:35 UTC, kalashnikovisme commented on app/controllers/answers_controller.rb
>      respond_to do |format|
Предлагаю везде убрать respond_to.

вместо строк

```ruby
if @answer.save
  redirect_to @answer.question, notice: 'Answer was created!'}
else
  render action: 'new'
end
```

почему надо так делать? Ты в этом экшне возвращаешь только html. json ты не возвращаешь, соответственно. Можно убрать эти строки и respond_to.

2016-11-14 22:35 UTC, kalashnikovisme commented on app/controllers/answers_controller.rb
> +  end
вместо этого будем использовать гем reform. https://github.com/apotonick/reform

как им пользоваться, покажу лично.

2016-11-14 22:35 UTC, kalashnikovisme commented on app/models/answer.rb
> +  default_scope -> {order('created_at DESC')}
default_scope - это плохая затея. Его можно спокойно убрать.

2016-11-14 22:35 UTC, kalashnikovisme commented on lib/tasks/sample_data.rake
> +                 date_creation: "14.11.16")
date_creation стоит убрать.

2016-11-14 22:35 UTC, kalashnikovisme commented on spec/factories.rb
> +end
лучше создать папку spec/factories
и там создать два файла spec/factories/questions.rb и spec/factories/answers.rb и разнести эти фабрики по двум файлам. Пример файла spec/factories/questions.rb. Второй сделаешь сама.

```ruby
FactoryGirl.define do
  factory :question do
    sequence(:title)  { |n| "Title #{n}" }
    sequence(:message) { |n| "Message #{n}"}
    sequence(:autor_name) {|n| "Autor_name #{n}"}
    date_creation "15.11.2016"
  end
end
```

2016-11-14 22:35 UTC, kalashnikovisme commented on spec/helpers/answers_helper_spec.rb
>  # the AnswersHelper. For example:
тестировать helpers не обязательно. Файл можешь убрать.

2016-11-14 22:35 UTC, kalashnikovisme commented on spec/models/question_spec.rb
> +    end
можно добавить в `rails_helper` такую строчку кода. Внутрь `RSpec.configure do` области

```ruby
config.include FactoryGirl::Syntax::Methods
```

эта строка вставляет функции FactoryGirl в тесты, и можно использовать более человекочитаемый 

```ruby
create :answer, question: @question
```

вместо строки выше.

2016-11-15 05:46 UTC, T-Midnight commented on app/models/answer.rb
> +  default_scope -> {order('created_at DESC')}
Без него ответы не появляются на странице в хронологическом порядке.

2016-11-16 10:48 UTC, kalashnikovisme requested changes

2016-11-16 10:48 UTC, kalashnikovisme commented on app/controllers/questions_controller.rb
> +end
мне кажется, ты вывела private за пределу контроллера.

2016-11-16 10:48 UTC, kalashnikovisme commented on app/models/answer.rb
> +  default_scope -> {order('created_at DESC')}
убери default_scope. Коллекция по умолчанию упорядочивается по created_at.

2016-11-16 10:48 UTC, kalashnikovisme commented on app/views/layouts/_header.html.erb
> +      <li role="presentation" class="active"><a href="http://localhost:3000/questions">Home</a></li>
Надо использовать относительные адреса, потому что ты выгрузишь это в продакшн, где будет какой-то домен вместо localhost:3000 - это не сработает. Надо использовать относительный адрес `/questions`.
`questions_path` метод вернёт тебе относительный адрес.

2016-11-16 10:48 UTC, kalashnikovisme commented on spec/rails_helper~
> +end
что это за файл?

2016-11-16 10:49 UTC, kalashnikovisme commented
Удали все файлы папки tmp/ из гита.

2016-11-16 10:56 UTC, kalashnikovisme commented
И теперь тесты не проходят.

2016-11-25 12:15 UTC, T-Midnight commented
@aelaa

2016-11-25 12:52 UTC, aelaa commented on log/test.log
> +  [1m[36m (0.1ms)[0m  [1mROLLBACK[0m
добавь папку logs в .gitignore)

2016-11-25 12:52 UTC, aelaa commented on tmp/pids/server.pid
> -3354
и папку tmp тоже

2016-12-12 11:38 UTC, aelaa commented
сделай `git rm -r tmp/`
остальное всё хорошо

2016-12-12 12:57 UTC, merged